name: Trigger RDP Workflow

on:
  workflow_dispatch:

permissions:
  actions: write   # 👈 THIS FIXES YOUR ERROR
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RDP workflow
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/razePro/Rdp_project/actions/workflows/rdp.yml/dispatches \
          -d '{"ref":"RDP"}'
